import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className = "flex gap-4 p-4 bg-gray-200 dark:bg-gray-800 text-lg font-semibold flex justify-center fixed w-full top-0">
          <a href="/">Home</a>
          <a href="/NativeAmerican">Native American</a>
          <a href="/European">European</a>
          <a href="/HispanicLatino">Hispanic and Latino</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
